// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace SchedulerBot.Database.Core.Migrations
{
	[DbContext(typeof(SchedulerBotContext))]
	[Migration("20180420113221_OccurrenceTypo")]
	partial class OccurrenceTypo
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "2.0.1-rtm-125")
				.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

			modelBuilder.Entity("SchedulerBot.Database.Entities.ScheduledMessage", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd();

					b.Property<string>("Schedule")
						.IsRequired();

					b.Property<int>("State");

					b.Property<string>("Text")
						.IsRequired();

					b.HasKey("Id");

					b.ToTable("ScheduledMessages");
				});

			modelBuilder.Entity("SchedulerBot.Database.Entities.ScheduledMessageDetails", b =>
				{
					b.Property<Guid>("ScheduledMessageId");

					b.Property<string>("ChannelId")
						.IsRequired();

					b.Property<string>("ConversationId")
						.IsRequired();

					b.Property<string>("FromId")
						.IsRequired();

					b.Property<string>("FromName")
						.IsRequired();

					b.Property<string>("Locale");

					b.Property<string>("RecipientId")
						.IsRequired();

					b.Property<string>("RecipientName")
						.IsRequired();

					b.Property<TimeSpan?>("TimeZoneOffset");

					b.HasKey("ScheduledMessageId");

					b.ToTable("ScheduledMessageDetails");
				});

			modelBuilder.Entity("SchedulerBot.Database.Entities.ScheduledMessageDetailsServiceUrl", b =>
				{
					b.Property<Guid>("DetailsId");

					b.Property<Guid>("ServiceUrlId");

					b.Property<DateTime>("CreatedOn");

					b.HasKey("DetailsId", "ServiceUrlId");

					b.HasIndex("ServiceUrlId");

					b.HasIndex("DetailsId", "ServiceUrlId", "CreatedOn");

					b.ToTable("ScheduledMessageDetailsServiceUrls");
				});

			modelBuilder.Entity("SchedulerBot.Database.Entities.ScheduledMessageEvent", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd();

					b.Property<DateTime>("CreatedOn");

					b.Property<DateTime>("NextOccurrence");

					b.Property<Guid>("ScheduledMessageId");

					b.Property<int>("State");

					b.HasKey("Id");

					b.HasIndex("ScheduledMessageId");

					b.ToTable("ScheduledMessageEvents");
				});

			modelBuilder.Entity("SchedulerBot.Database.Entities.ServiceUrl", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd();

					b.Property<string>("Address")
						.IsRequired();

					b.Property<DateTime>("CreatedOn");

					b.HasKey("Id");

					b.HasIndex("Address")
						.IsUnique();

					b.ToTable("ServiceUrls");
				});

			modelBuilder.Entity("SchedulerBot.Database.Entities.ScheduledMessageDetails", b =>
				{
					b.HasOne("SchedulerBot.Database.Entities.ScheduledMessage", "ScheduledMessage")
						.WithOne("Details")
						.HasForeignKey("SchedulerBot.Database.Entities.ScheduledMessageDetails", "ScheduledMessageId")
						.OnDelete(DeleteBehavior.Restrict);
				});

			modelBuilder.Entity("SchedulerBot.Database.Entities.ScheduledMessageDetailsServiceUrl", b =>
				{
					b.HasOne("SchedulerBot.Database.Entities.ScheduledMessageDetails", "Details")
						.WithMany("DetailsServiceUrls")
						.HasForeignKey("DetailsId")
						.OnDelete(DeleteBehavior.Restrict);

					b.HasOne("SchedulerBot.Database.Entities.ServiceUrl", "ServiceUrl")
						.WithMany("ServiceUrlMessageDetails")
						.HasForeignKey("ServiceUrlId")
						.OnDelete(DeleteBehavior.Restrict);
				});

			modelBuilder.Entity("SchedulerBot.Database.Entities.ScheduledMessageEvent", b =>
				{
					b.HasOne("SchedulerBot.Database.Entities.ScheduledMessage", "ScheduledMessage")
						.WithMany("Events")
						.HasForeignKey("ScheduledMessageId")
						.OnDelete(DeleteBehavior.Restrict);
				});
#pragma warning restore 612, 618
		}
	}
}
