// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System;

namespace SchedulerBot.Database.Core.Migrations
{
    [DbContext(typeof(SchedulerBotContext))]
    partial class SchedulerBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("SchedulerBot.Database.Entities.ScheduledMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConversationId")
                        .IsRequired();

                    b.Property<string>("Cron")
                        .IsRequired();

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ScheduledMessages");
                });

            modelBuilder.Entity("SchedulerBot.Database.Entities.ScheduledMessageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<Guid>("ScheduledMessageId");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledMessageId");

                    b.ToTable("ScheduledMessageLogs");
                });

            modelBuilder.Entity("SchedulerBot.Database.Entities.ScheduledMessageLog", b =>
                {
                    b.HasOne("SchedulerBot.Database.Entities.ScheduledMessage", "ScheduledMessage")
                        .WithMany("Logs")
                        .HasForeignKey("ScheduledMessageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
